### ISSUE TITLE
It looks like you've lost your domain name. ☹️

### ISSUE THREAD

**Issue by MailYouLater** [BenNottelling/bennottelling#1]
If I go to [Freenom](https://www.freenom.com/) and search for `bennottelling.ml`, it says I can get it, so unless someone else snatches it up before you do, you should be able to get it back.

**Comment by BenNottelling** [comment]
I'm using BenNottelling.com now ;) 
Have been for a while

**Comment by MailYouLater** [comment]
Oh, well in that case, you should change the references to the old `.ml` domain to point to the new `.com` domain.

i.e.: https://github.com/BenNottelling/bennottelling/blob/b1971511c998d84cc2519d6da6de5b634eb997b9/index.html#L15
https://github.com/BenNottelling/bennottelling/blob/b1971511c998d84cc2519d6da6de5b634eb997b9/webp.html#L15
[](![image](https://user-images.githubusercontent.com/1279475/67719522-3406a100-f98f-11e9-8df1-b9fe14d15d6f.png))

**Comment by MailYouLater** [comment]
Sorry for not checking back on this earlier.
Looks like you fixed this in commit 51bb5b4a0e3866faf7e8ce96c928d99bf8e5ff9d.
